### ISSUE TITLE
Unknown message type: IPM.Microsoft.ScheduleData.FreeBusy

### ISSUE THREAD

**Issue by biggert** [rjohnsondev/java-libpst#29]
When processing items out of the root folder with this particular [PST](https://drive.google.com/file/d/0B46Nalq8Xq0ZOUFzN05OXy1WZ0k/view?usp=sharing), I get an error that says "Unknown message type: IPM.Microsoft.ScheduleData.FreeBusy" when it gets to the last item.

I modified PSTObject to handle this particular type of messageClass and intended to submit a PR for it but I wasn't sure what object it should become.

**Comment by nickbuller** [comment]
Hi Biggert,

Thanks for reporting this issue, having looked at the PST file you provided, I see that this message class should not really map onto any of the existing classes due to the fact that there is almost no useful information in this PSTObject, if one was to be chosen then PSTAppointment would be best but would require decoding of the PidTag below. 

From the available properties I see in only PidTagScheduleInfoAppointmentTombstone looks to be of minor interest. If you are specifically interested in the data in the PSTObject then please do let me know.

You could work around this issue by not processing the folder with a displayname of "Freebusy Data", The fact you see this folder implies that your date is from Exchange pre 2007, can you confirm this?

Please note you will get these messages for other un mapped message types (Out Of Office, Quote Warnings etc...,) so again if you need anything from them let us know...

Regards,

Nick

**Comment by biggert** [comment]
@nickbuller To be honest, I've forgotten where it came from... we have a growing repository of PST files for testing. I agree with your assessment that these objects appear to provide no useful information (at least, to us) so your recommendation to work around the "Freebusy" folder is what we'll do. Thank you for the prompt response.
